#  My version of the school.py from the book
# The K-12 education system in U.S.A when I was younger

print("*** USA Education System ***","\n")
print("ELEMENTARY SCHOOL")
print("Kindergarten: K")
print("1st Grade: 1st")
print("2nd Grade: 2nd")
print("3rd Grade: 3rd")
print("4th Grade: 4th")
print("5th Grade: 5th")
print("6th Grade: 6th")
print()
print("MIDDLE SCHOOL")
print("7th Grade: 7th")
print("8th Grade: 8th")
print()
print("HIGH SCHOOL")
print("9th Grade: 9th")
print("10th Grade: 10th")
print("11th Grade: 11th")
print("12th Grade: 12th")
print()
print("*** GRADUATION ***")